package com.example.lotteryapp;

import android.graphics.Bitmap;
import android.graphics.Canvas;
import android.graphics.Color;
import android.graphics.Paint;
import android.graphics.Rect;
import android.graphics.Typeface;
import android.net.Uri;
import android.util.Log;

import com.google.firebase.storage.FirebaseStorage;
import com.google.firebase.storage.StorageReference;
import com.google.firebase.storage.UploadTask;

import java.io.ByteArrayOutputStream;

/**
 * The ProfileImage class provides methods to generate and upload profile images.
 * It allows the creation of arbitrary profile images based on a user's name
 * or the upload of user-selected images to Firebase Storage.
 * <p>
 * The generated profile images display the first letter of the user's name
 * on a randomly colored background. If no image is provided, a default image is generated.
 * </p>
 *
 * @see FirebaseStorage
 * @see StorageReference
 * @see Bitmap
 * @see Uri
 * @see ProfileImageCallback
 */
public class ProfileImage {

    private static final String TAG = "ProfileImage";

    /**
     * Generates a profile image represented by the first letter of the user's name
     * on a randomly colored background.
     * <p>
     * The image will have a size of 200x200 pixels, with the first letter of the name
     * drawn in the center of the image. The background color is randomly generated.
     * </p>
     *
     * @param name The name used to create the profile image. The first letter of the name
     *             will be displayed on the image.
     * @return A Bitmap object representing the generated profile image with the first letter
     *         of the name on a randomly colored background.
     * @throws NullPointerException if the provided name is null.
     * @see Bitmap
     * @see Canvas
     * @see Paint
     */
    // Generate an arbitrary picture for the given name
    public Bitmap generateArbitraryPicture(String name) {
        int size = 200; // Size of the profile image
        Bitmap bitmap = Bitmap.createBitmap(size, size, Bitmap.Config.ARGB_8888);
        Canvas canvas = new Canvas(bitmap);

        // Generate background color
        int backgroundColor = generateRandomColor();
        canvas.drawColor(backgroundColor);

        // Draw the first letter of the name
        String firstLetter = name.substring(0, 1).toUpperCase();
        Paint textPaint = new Paint();
        textPaint.setColor(Color.WHITE);
        textPaint.setTextSize(80); // Adjust text size as needed
        textPaint.setTypeface(Typeface.DEFAULT_BOLD);
        textPaint.setAntiAlias(true);

        // Center the text
        Rect bounds = new Rect();
        textPaint.getTextBounds(firstLetter, 0, firstLetter.length(), bounds);
        int x = (canvas.getWidth() / 2) - (bounds.width() / 2);
        int y = (canvas.getHeight() / 2) + (bounds.height() / 2);

        canvas.drawText(firstLetter, x, y, textPaint);

        return bitmap;
    }

    /**
     * Helper method to generate a random RGB color.
     * The color is generated by creating random values for red, green, and blue channels.
     *
     * @return An integer representing the randomly generated RGB color.
     * @see Color
     */
    // Helper method to generate a random color
    private int generateRandomColor() {
        return Color.rgb(
                (int) (Math.random() * 255),
                (int) (Math.random() * 255),
                (int) (Math.random() * 255)
        );
    }

    /**
     * Uploads a profile image to Firebase Storage. If an image URI is provided, the image
     * is uploaded directly; if no URI is provided, a default image is generated and uploaded.
     *
     * @param entrantId The ID of the entrant for whom the image is being uploaded.
     * @param imageUri The URI of the image to be uploaded. If null, a generated image will be uploaded.
     * @param name The name of the entrant, used to generate a default image if no image URI is provided.
     * @param callback A callback that will be invoked upon success or failure of the image upload.
     * @throws IllegalArgumentException if the entrantId is null or empty.
     * @see FirebaseStorage
     * @see StorageReference
     * @see ProfileImageCallback
     */
    // Save or upload the provided URI image or generate a default image if none exists
    public void uploadImageToFirebase(String entrantId, Uri imageUri, String name, ProfileImageCallback callback) {
        FirebaseStorage storage = FirebaseStorage.getInstance();
        StorageReference storageRef = storage.getReference();
        StorageReference imageRef;

        if (imageUri != null) {
            // Store user-uploaded images in the profile-images/ folder
            imageRef = storageRef.child("profile-images/" + entrantId + ".png");
            uploadImageFromUri(imageUri, imageRef, callback);
        } else {
            // Store generated images in the generated-images/ folder
            imageRef = storageRef.child("generated-images/" + entrantId + ".png");
            Bitmap generatedBitmap = generateArbitraryPicture(name);
            uploadGeneratedImage(imageRef, generatedBitmap, callback);
        }
    }

    /**
     * Uploads a user-selected image from a URI to Firebase Storage.
     *
     * @param imageUri The URI of the image to upload.
     * @param imageRef The Firebase Storage reference where the image will be uploaded.
     * @param callback A callback to handle success or failure of the upload.
     * @see FirebaseStorage
     * @see StorageReference
     * @see ProfileImageCallback
     */
    // Upload a user-selected URI image to Firebase Storage
    private void uploadImageFromUri(Uri imageUri, StorageReference imageRef, ProfileImageCallback callback) {
        imageRef.putFile(imageUri)
                .addOnSuccessListener(taskSnapshot -> imageRef.getDownloadUrl().addOnSuccessListener(uri -> {
                    Log.d(TAG, "Image uploaded successfully: " + uri.toString());
                    callback.onSuccess(uri.toString());
                }))
                .addOnFailureListener(e -> {
                    Log.e(TAG, "Image upload failed: " + e.getMessage());
                    callback.onFailure(e);
                });
    }

    /**
     * Uploads a generated Bitmap image to Firebase Storage.
     *
     * @param imageRef The Firebase Storage reference where the image will be uploaded.
     * @param bitmap The Bitmap image to be uploaded.
     * @param callback A callback to handle success or failure of the upload.
     * @see FirebaseStorage
     * @see StorageReference
     * @see ProfileImageCallback
     */
    // Upload a generated Bitmap to Firebase Storage
    private void uploadGeneratedImage(StorageReference imageRef, Bitmap bitmap, ProfileImageCallback callback) {
        ByteArrayOutputStream baos = new ByteArrayOutputStream();
        bitmap.compress(Bitmap.CompressFormat.PNG, 100, baos);
        byte[] data = baos.toByteArray();

        UploadTask uploadTask = imageRef.putBytes(data);
        uploadTask.addOnFailureListener(e -> {
            Log.e(TAG, "Generated image upload failed: " + e.getMessage());
            callback.onFailure(e);
        }).addOnSuccessListener(taskSnapshot -> {
            imageRef.getDownloadUrl().addOnSuccessListener(uri -> {
                Log.d(TAG, "Generated image uploaded successfully: " + uri.toString());
                callback.onSuccess(uri.toString());
            });
        });
    }

    /**
     * Callback interface to handle success and failure events of the image upload process.
     *
     * @see ProfileImage
     */
    public interface ProfileImageCallback {

        /**
         * Called when the image upload is successful.
         *
         * @param imageUrl The URL of the uploaded image.
         */
        void onSuccess(String imageUrl);

        /**
         * Called when the image upload fails.
         *
         * @param e The exception that caused the failure.
         */
        void onFailure(Exception e);
    }
}
